// Copyright 2026 Phillip Cloud
// Licensed under the Apache License, Version 2.0

// Code generated by gencolumns; DO NOT EDIT.

package app

type projectCol int

const (
	projectColID projectCol = iota
	projectColType
	projectColTitle
	projectColStatus
	projectColBudget
	projectColActual
	projectColStart
	projectColEnd
	projectColQuotes
	projectColDocs
)

type quoteCol int

const (
	quoteColID quoteCol = iota
	quoteColProject
	quoteColVendor
	quoteColTotal
	quoteColLabor
	quoteColMat
	quoteColOther
	quoteColRecv
	quoteColDocs
)

type maintenanceCol int

const (
	maintenanceColID maintenanceCol = iota
	maintenanceColItem
	maintenanceColCategory
	maintenanceColSeason
	maintenanceColAppliance
	maintenanceColLast
	maintenanceColNext
	maintenanceColEvery
	maintenanceColLog
	maintenanceColDocs
)

type incidentCol int

const (
	incidentColID incidentCol = iota
	incidentColTitle
	incidentColStatus
	incidentColSeverity
	incidentColLocation
	incidentColAppliance
	incidentColVendor
	incidentColNoticed
	incidentColResolved
	incidentColCost
	incidentColDocs
)

type applianceCol int

const (
	applianceColID applianceCol = iota
	applianceColName
	applianceColBrand
	applianceColModel
	applianceColSerial
	applianceColLocation
	applianceColPurchased
	applianceColAge
	applianceColWarranty
	applianceColCost
	applianceColMaint
	applianceColDocs
)

type vendorCol int

const (
	vendorColID vendorCol = iota
	vendorColName
	vendorColContact
	vendorColEmail
	vendorColPhone
	vendorColWebsite
	vendorColQuotes
	vendorColJobs
	vendorColDocs
)

type serviceLogCol int

const (
	serviceLogColID serviceLogCol = iota
	serviceLogColDate
	serviceLogColPerformedBy
	serviceLogColCost
	serviceLogColNotes
	serviceLogColDocs
)

type vendorJobsCol int

const (
	vendorJobsColID vendorJobsCol = iota
	vendorJobsColItem
	vendorJobsColDate
	vendorJobsColCost
	vendorJobsColNotes
)

type documentCol int

const (
	documentColID documentCol = iota
	documentColTitle
	documentColEntity
	documentColType
	documentColSize
	documentColModel
	documentColNotes
	documentColUpdated
)
