# Copyright 2026 Phillip Cloud
# Licensed under the Apache License, Version 2.0

services:
  caddy:
    image: caddy@sha256:1e40b251ca9639ead7b5cd2cedcc8765adfbabb99450fe23f130eefabf50f4bc # 2-alpine
    environment:
      DOMAIN: ${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      relay:
        condition: service_healthy

  relay:
    ports: []

volumes:
  caddy_data:
  caddy_config:
