// Copyright 2026 Phillip Cloud
// Licensed under the Apache License, Version 2.0

// genmeta generates table/column name constants and per-table extractable
// column metadata from GORM model structs. Everything is derived from the
// models.go AST: struct names, field names, struct tags, and field types.
// The generator does NOT import the data package -- it reads the source text
// and applies GORM's NamingStrategy for table/column name conversion.
//
// Usage: go generate ./internal/data/
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/iancoleman/strcase"
	"gorm.io/gorm/schema"
)

func main() {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "models.go", nil, 0)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse models.go: %v\n", err)
		os.Exit(1)
	}

	structs, structNames := collectStructs(f)
	if len(structs) == 0 {
		fmt.Fprintf(os.Stderr, "no exported struct types found in models.go\n")
		os.Exit(1)
	}

	namer := schema.NamingStrategy{}
	year := time.Now().UTC().Year()

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Copyright %d Phillip Cloud\n", year)
	buf.WriteString("// Licensed under the Apache License, Version 2.0\n\n")
	buf.WriteString("// Code generated by genmeta; DO NOT EDIT.\n\n")
	buf.WriteString("package data\n\n")

	tableConsts := make(map[string]string)          // "TableVendors" -> "vendors"
	colConsts := make(map[string]string)            // "ColVendorID"  -> "vendor_id"
	extractCols := make(map[string][]extractColumn) // "vendors" -> [{name, string}, ...]

	for _, s := range structs {
		tableName := namer.TableName(s.name)
		tableConsts["Table"+strcase.ToCamel(tableName)] = tableName

		for _, field := range s.fields {
			if isAssociation(field.Type, structNames) {
				continue
			}

			for _, ident := range field.Names {
				if !ident.IsExported() {
					continue
				}

				gormTag := fieldGormTag(field)
				if gormTag == "-" {
					continue
				}

				dbName := gormColumnName(gormTag)
				if dbName == "" {
					dbName = namer.ColumnName("", ident.Name)
				}

				key := "Col" + ident.Name
				if existing, ok := colConsts[key]; ok && existing != dbName {
					fmt.Fprintf(os.Stderr,
						"column name conflict: %s maps to both %q and %q\n",
						key, existing, dbName,
					)
					os.Exit(1)
				}
				colConsts[key] = dbName

				// Collect extractable columns: skip auto-managed fields,
				// binary data, extract:"-" tagged fields, and types
				// we can't map to JSON Schema.
				if gormAutoFields[ident.Name] || isByteSlice(field.Type) ||
					fieldExtractTag(field) == "-" {
					continue
				}
				if jt := jsonSchemaType(field.Type); jt != "" {
					extractCols[tableName] = append(extractCols[tableName], extractColumn{
						dbName:   dbName,
						jsonType: jt,
					})
				}
			}
		}
	}

	writeConstBlock(&buf, "// Table name constants derived from GORM model structs.", tableConsts)
	buf.WriteByte('\n')
	writeConstBlock(&buf, "// Column name constants derived from GORM model structs.", colConsts)
	buf.WriteByte('\n')
	writeModelsFunc(&buf, structs)
	buf.WriteByte('\n')
	writeExtractColumns(&buf, extractCols)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "gofmt: %v\n", err)
		if _, wErr := os.Stderr.Write(buf.Bytes()); wErr != nil {
			fmt.Fprintf(os.Stderr, "write stderr: %v\n", wErr)
		}
		os.Exit(1)
	}

	if err := os.WriteFile("meta_generated.go", src, 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
}

// writeConstBlock emits a sorted const block with the given comment header.
func writeConstBlock(buf *bytes.Buffer, comment string, consts map[string]string) {
	keys := make([]string, 0, len(consts))
	for k := range consts {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	buf.WriteString(comment + "\n")
	buf.WriteString("const (\n")
	for _, k := range keys {
		fmt.Fprintf(buf, "\t%s = %q\n", k, consts[k])
	}
	buf.WriteString(")\n")
}

// writeModelsFunc emits a Models() function that returns pointers to every
// GORM model struct, in source order.
func writeModelsFunc(buf *bytes.Buffer, structs []modelStruct) {
	buf.WriteString("// Models returns a pointer to every GORM model struct in source order.\n")
	buf.WriteString("// Used by AutoMigrate and FK introspection.\n")
	buf.WriteString("func Models() []any {\n")
	buf.WriteString("\treturn []any{\n")
	for _, s := range structs {
		fmt.Fprintf(buf, "\t\t&%s{},\n", s.name)
	}
	buf.WriteString("\t}\n")
	buf.WriteString("}\n")
}

type modelStruct struct {
	name   string
	fields []*ast.Field
}

// extractColumn holds the DB column name and JSON Schema type for a single
// extractable column. Used to generate TableExtractColumns.
type extractColumn struct {
	dbName   string
	jsonType string // "string" or "integer"
}

// collectStructs walks the AST and returns all exported struct types in source
// order, along with a set of their names (used to identify association fields).
func collectStructs(f *ast.File) ([]modelStruct, map[string]bool) {
	var structs []modelStruct
	names := make(map[string]bool)

	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			if !ts.Name.IsExported() {
				continue
			}
			structs = append(structs, modelStruct{
				name:   ts.Name.Name,
				fields: st.Fields.List,
			})
			names[ts.Name.Name] = true
		}
	}

	return structs, names
}

// isAssociation returns true when the field type (after removing pointer or
// slice wrapper) matches a local exported struct name. GORM treats these as
// associations (BelongsTo, HasMany, etc.), not DB columns.
func isAssociation(expr ast.Expr, localStructs map[string]bool) bool {
	if star, ok := expr.(*ast.StarExpr); ok {
		expr = star.X
	}
	if arr, ok := expr.(*ast.ArrayType); ok {
		expr = arr.Elt
	}
	ident, ok := expr.(*ast.Ident)
	if !ok {
		return false
	}
	return localStructs[ident.Name]
}

// fieldExtractTag extracts the "extract" struct tag value from an AST field.
func fieldExtractTag(field *ast.Field) string {
	if field.Tag == nil {
		return ""
	}
	raw := field.Tag.Value[1 : len(field.Tag.Value)-1]
	return reflect.StructTag(raw).Get("extract")
}

// fieldGormTag extracts the "gorm" struct tag value from an AST field.
func fieldGormTag(field *ast.Field) string {
	if field.Tag == nil {
		return ""
	}
	// Strip surrounding backticks.
	raw := field.Tag.Value[1 : len(field.Tag.Value)-1]
	return reflect.StructTag(raw).Get("gorm")
}

// gormColumnName extracts the column name override from a gorm tag value.
// Returns "" when no column override is present.
func gormColumnName(tag string) string {
	for _, part := range strings.Split(tag, ";") {
		if strings.HasPrefix(part, "column:") {
			return strings.TrimPrefix(part, "column:")
		}
	}
	return ""
}

// gormAutoFields are fields managed by GORM (primary key, timestamps,
// soft delete) that should not appear in extractable column metadata.
var gormAutoFields = map[string]bool{
	"ID":        true,
	"CreatedAt": true,
	"UpdatedAt": true,
	"DeletedAt": true,
}

// isByteSlice returns true for []byte AST types (binary data columns).
func isByteSlice(expr ast.Expr) bool {
	at, ok := expr.(*ast.ArrayType)
	if !ok {
		return false
	}
	// []byte has nil Len (slice, not array) and byte element type.
	if at.Len != nil {
		return false
	}
	ident, ok := at.Elt.(*ast.Ident)
	return ok && ident.Name == "byte"
}

// jsonSchemaType maps a Go AST type expression to a JSON Schema type string.
// Returns "" for types that should be excluded from extraction metadata
// (e.g. gorm.DeletedAt, []byte).
func jsonSchemaType(expr ast.Expr) string {
	// Unwrap pointer.
	if star, ok := expr.(*ast.StarExpr); ok {
		return jsonSchemaType(star.X)
	}

	// Simple identifiers: string, int, int64, uint, float64.
	if ident, ok := expr.(*ast.Ident); ok {
		switch ident.Name {
		case "string":
			return "string"
		case "int", "int64", "uint", "float64":
			return "integer"
		}
		return ""
	}

	// Selector expressions: time.Time -> "string", gorm.DeletedAt -> "".
	if sel, ok := expr.(*ast.SelectorExpr); ok {
		if pkg, ok := sel.X.(*ast.Ident); ok {
			if pkg.Name == "time" && sel.Sel.Name == "Time" {
				return "string"
			}
		}
		return ""
	}

	return ""
}

// writeExtractColumns emits the MetaColumn type and TableExtractColumns map.
func writeExtractColumns(buf *bytes.Buffer, extractCols map[string][]extractColumn) {
	buf.WriteString("// metaColumn describes a single DB column's name and JSON Schema type.\n")
	buf.WriteString("// Used by the extraction system to derive column definitions from models.\n")
	buf.WriteString("type metaColumn struct {\n")
	buf.WriteString("\tName     string\n")
	buf.WriteString("\tJSONType string // \"string\" or \"integer\"\n")
	buf.WriteString("}\n\n")

	tables := make([]string, 0, len(extractCols))
	for t := range extractCols {
		tables = append(tables, t)
	}
	sort.Strings(tables)

	buf.WriteString("// TableExtractColumns maps each table to its extractable columns.\n")
	buf.WriteString("// Excludes primary keys, auto-managed timestamps, soft-delete markers,\n")
	buf.WriteString("// GORM association fields, and binary data columns.\n")
	buf.WriteString("var TableExtractColumns = map[string][]metaColumn{\n")
	for _, table := range tables {
		cols := extractCols[table]
		if len(cols) == 0 {
			continue
		}
		// Use the Table constant name.
		constName := "Table" + strcase.ToCamel(table)
		fmt.Fprintf(buf, "\t%s: {\n", constName)
		for _, col := range cols {
			fmt.Fprintf(buf, "\t\t{Name: %q, JSONType: %q},\n", col.dbName, col.jsonType)
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")
}
