# Copyright 2026 Phillip Cloud
# Licensed under the Apache License, Version 2.0

name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  deadcode:
    name: Dead Code
    runs-on: ubuntu-latest
    concurrency:
      group: lint-deadcode-${{ github.ref }}
      cancel-in-progress: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@19effe9fe722874e6d46dd7182e4b8b7a43c4a99 # v31.10.0

      - name: Run deadcode
        run: nix run '.#deadcode'

  golangci-lint:
    name: Lint
    runs-on: ubuntu-latest
    concurrency:
      group: lint-golangci-lint-${{ github.ref }}
      cancel-in-progress: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@19effe9fe722874e6d46dd7182e4b8b7a43c4a99 # v31.10.0

      - name: Run golangci-lint
        run: nix run '.#golangci-lint'

  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    concurrency:
      group: lint-pre-commit-${{ github.ref }}
      cancel-in-progress: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: cachix/install-nix-action@19effe9fe722874e6d46dd7182e4b8b7a43c4a99 # v31.10.0

      - name: Run pre-commit hooks
        run: nix run '.#pre-commit' -- --from-ref 'origin/${{ github.base_ref || 'main' }}' --to-ref HEAD
